release-date = "2020-07-03"

[[entries]]
id = "d94874c1-7fc2-43e8-b6a1-54db3d1d808d"
type = "fix"
description = "No longer produce wheels when publishing to PyPI, readthedocs-custom-steps must be installed as a source distribution"
author = "@NiklasRosenstein"
