name: readthedocs-custom-steps
version: 0.4.0
license: MIT
author:
  name: Niklas Rosenstein
  email: rosensteinniklas@gmail.com

url: https://github.com/NiklasRosenstein/readthedocs-custom-steps/
description: A hack to run custom steps when building documentation on Read the Docs.
readme: ../README.md

wheel: False
install:
  hooks:
    before-install:
    - bin/install-hack.py

requirements:
- python ^3.5
- PyYAML ^5.0

test-requirements:
- docker ^5.0.0
- six  # because of docker==5.0.0 (see https://github.com/docker/docker-py/issues/2867)
- types-PyYAML

test-drivers:
- type: pytest
  parallelism: 8
- type: mypy
