name: readthedocs-custom-steps
version: 0.2.1
author:
  name: Niklas Rosenstein
  email: rosensteinniklas@gmail.com
description: A hack to run custom steps when building documentation on Read the Docs.
readme: ../README.md
requirements:
- python ^3.5
- PyYAML ^5.0
install-hooks:
- install: bin/install-hack.py
manifest:
- include bin/install-hack.py
