name: readthedocs-custom-steps
version: 0.3.0
author:
  name: Niklas Rosenstein
  email: rosensteinniklas@gmail.com
description: A hack to run custom steps when building documentation on Read the Docs.
url: https://github.com/NiklasRosenstein/readthedocs-custom-steps/
readme: ../README.md
requirements:
- python ^3.5
- PyYAML ^5.0
install-hooks:
- install: bin/install-hack.py
manifest:
- include bin/install-hack.py
wheel: False
